/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaodien;

import dao.QLSVDao;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Diem;
import pojo.Lop;
import pojo.Tkbieu;
import pojo.Tkdangnhap;

/**
 *
 * @author HP
 */
public class ManagerMenu extends javax.swing.JFrame {

    private DefaultTableModel dftm;
    private ArrayList<Lop> listLop;
    private DefaultTableModel dfmDsLop;
    private ArrayList<Lop> DSLop;
    private DefaultTableModel dfmDiem;
    private ArrayList<Diem> DSDiem;
    private DefaultTableModel dfmXemDiem;
    private ArrayList<Diem> DSDiemCanChinh;
    int selectedIndexTB;
    private DefaultTableModel dfmThemTKB;
    private ArrayList<Tkbieu> TKBieu;
    /**
     * Creates new form NewJFrame
     */
    private void myinit()
    {
        dftm = (DefaultTableModel) tblop.getModel();
        dfmDsLop=(DefaultTableModel) tbDSLop.getModel();
        dfmDiem = (DefaultTableModel) tbDiem.getModel();
        listLop = new ArrayList<Lop>();
        DSLop = new ArrayList<Lop>();
        DSDiem = new ArrayList<Diem>();
        dfmXemDiem=(DefaultTableModel) tbXemDiem.getModel();
        DSDiemCanChinh = new ArrayList<>();
        dfmThemTKB = (DefaultTableModel) tbThemTKB.getModel();
        TKBieu = new ArrayList<Tkbieu>();
    }
    public ManagerMenu() {
        initComponents();
        myinit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lbError = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        edtLop = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edtCMND = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnThemSinhVien = new javax.swing.JButton();
        edtMSSV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtHoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edtGioiTinh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtTenLop = new javax.swing.JTextField();
        btnXemThongTinLop = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDSLop = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lbfile = new javax.swing.JLabel();
        btnChonFile = new javax.swing.JButton();
        btnThemDSLop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblop = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        lbFileDiem = new javax.swing.JLabel();
        btnChonFileDiemCSV = new javax.swing.JButton();
        btnThemDiemVaoHT = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDiem = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        edtLopDiem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnXemDiem = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbXemDiem = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbMSSV = new javax.swing.JLabel();
        lbMon = new javax.swing.JLabel();
        edtDiemGK = new javax.swing.JTextField();
        edtDiemCK = new javax.swing.JTextField();
        edtDiemKhac = new javax.swing.JTextField();
        edtTongDiem = new javax.swing.JTextField();
        btnLuuThayDoiDiem = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbDau = new javax.swing.JLabel();
        lbRot = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnThemTKB = new javax.swing.JButton();
        lbFileTKB = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbThemTKB = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbError.setForeground(new java.awt.Color(255, 0, 0));

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        edtLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtLopActionPerformed(evt);
            }
        });

        jLabel5.setText("Lớp");

        jLabel6.setText("CMND");

        btnThemSinhVien.setText("Thêm sinh viên");
        btnThemSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSinhVienActionPerformed(evt);
            }
        });

        jLabel2.setText("MSSV");

        jLabel4.setText("Giới tính");

        jLabel3.setText("Ho Tên");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThemSinhVien)
                                    .addComponent(edtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(edtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(166, 166, 166))
                            .addComponent(edtLop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(edtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(edtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemSinhVien))))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Thêm sinh viên", jPanel7);

        jLabel1.setText("Nhập lớp cần xem");

        btnXemThongTinLop.setText("Xem thông tin");
        btnXemThongTinLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemThongTinLopActionPerformed(evt);
            }
        });

        tbDSLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MSSV", "Ho Ten", "GioiTinh", "Lop", "CMND"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbDSLop);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(edtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(btnXemThongTinLop)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemThongTinLop))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("xem danh sách lớp", jPanel8);

        lbfile.setBackground(new java.awt.Color(153, 153, 153));
        lbfile.setText("file csv");
        lbfile.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnChonFile.setText("Chọn file csv");
        btnChonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonFileActionPerformed(evt);
            }
        });

        btnThemDSLop.setText("Thêm vào hệ thống");
        btnThemDSLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDSLopActionPerformed(evt);
            }
        });

        tblop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MSSV", "Ho Ten", "Gioi Tinh", "Lop", "CMND"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblop);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbfile, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnChonFile, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThemDSLop)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChonFile)
                    .addComponent(lbfile)
                    .addComponent(btnThemDSLop))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Thêm danh sách lớp", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(lbError, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbError, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sinh viên", jPanel2);

        jTabbedPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbFileDiem.setText("file csv");
        lbFileDiem.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnChonFileDiemCSV.setText("Chọn file csv");
        btnChonFileDiemCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonFileDiemCSVActionPerformed(evt);
            }
        });

        btnThemDiemVaoHT.setText("Thêm vào hệ thống");
        btnThemDiemVaoHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDiemVaoHTActionPerformed(evt);
            }
        });

        tbDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MSSV", "Môn", "Lớp", "Điểm GK", "Điểm CK", "Điểm khác", "Tổng điểm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbDiem);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnChonFileDiemCSV)
                        .addGap(32, 32, 32)
                        .addComponent(btnThemDiemVaoHT)
                        .addGap(138, 138, 138))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbFileDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChonFileDiemCSV)
                    .addComponent(btnThemDiemVaoHT)
                    .addComponent(lbFileDiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Thêm điểm", jPanel9);

        edtLopDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtLopDiemActionPerformed(evt);
            }
        });

        jLabel7.setText("Chọn lớp");

        btnXemDiem.setText("Xem điểm");
        btnXemDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemDiemActionPerformed(evt);
            }
        });

        tbXemDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MSSV", "Môn", "Lop", "Điểm GK", "Điểm CK", "Điểm Khác", "Điểm tổng", "Kết quả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbXemDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbXemDiemMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbXemDiem);

        jLabel8.setText("MSSV");

        jLabel9.setText("Môn");

        jLabel10.setText("Điểm GK");

        jLabel11.setText("Điểm CK");

        jLabel12.setText("Điểm Khác");

        jLabel13.setText("Tổng điểm");

        lbMSSV.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbMon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLuuThayDoiDiem.setText("Lưu thay đổi");
        btnLuuThayDoiDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuThayDoiDiemActionPerformed(evt);
            }
        });

        jLabel14.setText("Đậu");

        jLabel15.setText("Rớt:");

        lbDau.setText("          ");
        lbDau.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbRot.setText("          ");
        lbRot.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edtLopDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnXemDiem)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDau)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbRot))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(lbMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(68, 68, 68))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(lbMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(32, 32, 32)))
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(edtDiemGK, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(edtDiemCK, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(edtDiemKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(edtTongDiem))
                                .addGap(40, 40, 40)
                                .addComponent(btnLuuThayDoiDiem)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(edtLopDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemDiem)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(lbDau)
                    .addComponent(lbRot))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edtDiemGK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edtDiemCK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edtDiemKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edtTongDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLuuThayDoiDiem))
                    .addComponent(lbMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMSSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Xem danh sách điểm", jPanel10);

        jLayeredPane1.setLayer(jTabbedPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Điểm", jLayeredPane1);

        btnThemTKB.setText("Thêm thời khóa biểu");
        btnThemTKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTKBActionPerformed(evt);
            }
        });

        lbFileTKB.setText("file csv");
        lbFileTKB.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setText("Chọn file csv");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbThemTKB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "stt", "Mã môn", "Tên môn", "Lớp", "Phòng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tbThemTKB);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbFileTKB, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(btnThemTKB)
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemTKB)
                    .addComponent(lbFileTKB)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Thêm thời khóa biểu", jPanel1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thời khóa biểu", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemDiemActionPerformed
        // TODO add your handling code here:
        String tenLop = edtLopDiem.getText();
        //ArrayList<Diem> dsDiem;
        DSDiemCanChinh = QLSVDao.layDSDiem(tenLop);
        if (DSDiemCanChinh.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "không có lớp cần tìm");
        } else {
            dfmXemDiem.setRowCount(0);
            String kq;
            int stt = 1;
            int demDau=0;
            for (int i = 0; i < DSDiemCanChinh.size(); i++) {
                if (DSDiemCanChinh.get(i).getKetQua() != 1) {
                    kq = "R";
                } else {
                    kq = "Đ";
                }

                String masv = DSDiemCanChinh.get(i).getMaSv();
                String maMon = DSDiemCanChinh.get(i).getMaMon();
                String lop = DSDiemCanChinh.get(i).getLop();
                float diemGK = DSDiemCanChinh.get(i).getDiemGk();
                float diemCK = DSDiemCanChinh.get(i).getDiemCk();
                float diemKhac = DSDiemCanChinh.get(i).getDiemKhac();
                float diemTong = DSDiemCanChinh.get(i).getTongDiem();
                int ketQua = DSDiemCanChinh.get(i).getKetQua();
                dfmXemDiem.addRow(new Object[]{stt++, masv, maMon, lop, diemGK, diemCK, diemKhac, diemTong, kq});
                if(ketQua==1)
                {
                    demDau++;
                }
            }
            float Dau = (float) demDau*100/DSDiemCanChinh.size();
            lbDau.setText(Dau + "%");
            lbRot.setText(100-Dau + "%");
        }
    }//GEN-LAST:event_btnXemDiemActionPerformed

    private void btnThemDiemVaoHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDiemVaoHTActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<DSDiem.size();i++)
        {
            QLSVDao.themDiem(DSDiem.get(i));
        }
        JOptionPane.showMessageDialog(rootPane, "thêm điểm vào hệ thống thành công");
    }//GEN-LAST:event_btnThemDiemVaoHTActionPerformed

    private void btnChonFileDiemCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonFileDiemCSVActionPerformed
        // TODO add your handling code here:
        JFileChooser chf = new JFileChooser();
        int check = chf.showOpenDialog(null);
        if(check==JFileChooser.APPROVE_OPTION)
        {

            String fileName = chf.getSelectedFile().getPath();
            lbFileDiem.setText(fileName);
            BufferedReader reader;
            String Line;
            try {
                reader = new BufferedReader(new FileReader(fileName));
                reader.readLine();
                int dem=1;
                dfmDiem.setRowCount(0);
                while((Line = reader.readLine())!=null)
                {
                    //JOptionPane.showMessageDialog(rootPane,"--" + Line+"--");
                    //Line = reader.readLine();
                    ArrayList a = (ArrayList) pastCSVLine(Line);
                    String masv = (String)a.get(1);
                    String mon = (String)a.get(2);
                    String lop=(String)a.get(3);
                    float diemGK=Float.parseFloat((String) a.get(4));
                    float diemCK=Float.parseFloat((String) a.get(5));
                    float diemKhac=Float.parseFloat((String) a.get(6));
                    float diemTong=Float.parseFloat((String) a.get(7));
                    int checkDau=1;
                    if(diemTong<5)
                    {
                        checkDau=0;
                    }
                    Diem diem = new Diem(masv,lop,mon,diemGK,diemCK,diemKhac,diemTong,checkDau);
                    DSDiem.add(diem);

                    dfmDiem.addRow(new Object[]{dem++,
                        diem.getMaSv(),
                        diem.getLop(),
                        diem.getMaMon(),
                        diem.getDiemGk(),
                        diem.getDiemCk(),
                        diem.getDiemKhac(),
                        diem.getTongDiem()});
                }
                reader.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManagerMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ManagerMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnChonFileDiemCSVActionPerformed

    private void btnThemDSLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDSLopActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<listLop.size();i++)
        {
            QLSVDao.themDanhSachLop(listLop.get(i));
            String ms = listLop.get(i).getMssv();
            Tkdangnhap tk = new Tkdangnhap(ms,ms,0);
            QLSVDao.themTaiKhoanDN(tk);
        }
        JOptionPane.showMessageDialog(rootPane, "thêm danh sách lớp thành công");
    }//GEN-LAST:event_btnThemDSLopActionPerformed

    private void btnChonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonFileActionPerformed
        // TODO add your handling code here:
        JFileChooser chf = new JFileChooser();
        int check = chf.showOpenDialog(null);
        if(check==JFileChooser.APPROVE_OPTION)
        {
            listLop.clear();
            String fileName = chf.getSelectedFile().getPath();
            lbfile.setText(fileName);
            BufferedReader reader;
            String Line;
            try {
                reader = new BufferedReader(new FileReader(fileName));
                Line = reader.readLine();
                int dem=1;
                dftm.setRowCount(0);
                while((Line = reader.readLine())!=null)
                {
                    //Line = reader.readLine();
                    List a = pastCSVLine(Line);

                    Lop lop = new Lop((String)a.get(1),(String)a.get(2),(String)a.get(3),(String)a.get(4),(String)a.get(5));
                    listLop.add(lop);

                    dftm.addRow(new Object[]{dem++,
                        lop.getMssv(),
                        lop.getHoTen(),
                        lop.getGioiTinh(),
                        lop.getLop(),
                        lop.getCmnd() });
            }
                reader.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManagerMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ManagerMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnChonFileActionPerformed

    private void btnXemThongTinLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemThongTinLopActionPerformed
        // TODO add your handling code here:
        String TenLop = edtTenLop.getText();
        if(TenLop.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập tên lớp");
        }
        else
        {
            //            int rows = dfmDsLop.getRowCount();
            //            for(int i=0;i<rows;i++)
            //            {
                //                dfmDsLop.removeRow(i);
                //            }
            dfmDsLop.setRowCount(0);
            if(!DSLop.isEmpty())
            DSLop.clear();
            DSLop = (ArrayList<Lop>) QLSVDao.layDanhSachLop(TenLop);
            if(DSLop.isEmpty())
            {
                JOptionPane.showMessageDialog(rootPane, "Không có lớp cần tìm");
            }
            else
            {
                for (int i = 0; i < DSLop.size(); i++)
                {
                    dfmDsLop.addRow(new Object[]{i + 1, DSLop.get(i).getMssv(), DSLop.get(i).getHoTen(),
                        DSLop.get(i).getGioiTinh(), DSLop.get(i).getLop(), DSLop.get(i).getCmnd()});
            }
        }
        }
    }//GEN-LAST:event_btnXemThongTinLopActionPerformed

    private void btnThemSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSinhVienActionPerformed
        // TODO add your handling code here:
        String MSSV = edtMSSV.getText();
        String HoTen = edtHoTen.getText();
        String GioiTinh=edtGioiTinh.getText();
        String Lop = edtLop.getText();
        String CMND = edtCMND.getText();
        String error="Điền đầy đủ thông tin";
        if(MSSV.equals("")||HoTen.equals("")||GioiTinh.equals("")||Lop.equals("")||CMND.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "bạn chưa điền đầy đủ thông tin");
        }
        else
        {
            Lop lp = new Lop(MSSV,HoTen,GioiTinh,Lop,CMND);
            if(QLSVDao.laySinhVien(MSSV)==null)
            {
                QLSVDao.themDanhSachLop(lp);
                Tkdangnhap tk = new Tkdangnhap(MSSV,MSSV,0);
                QLSVDao.themTaiKhoanDN(tk);
                
                JOptionPane.showMessageDialog(rootPane, "Thêm sinh viên thành công");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "MSSV đã tồn tại trong hệ thống");

            }

        }
    }//GEN-LAST:event_btnThemSinhVienActionPerformed

    private void edtLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtLopActionPerformed

    private void edtLopDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtLopDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtLopDiemActionPerformed

    private void tbXemDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbXemDiemMouseClicked
        // TODO add your handling code here:
        selectedIndexTB= tbXemDiem.getSelectedRow();
        Diem d=DSDiemCanChinh.get(selectedIndexTB);
        lbMSSV.setText(d.getMaSv());
        lbMon.setText(d.getMaMon());
        edtDiemGK.setText(d.getDiemGk()+"");
        edtDiemCK.setText(d.getDiemCk()+"");
        edtDiemKhac.setText(d.getDiemKhac()+"");
        edtTongDiem.setText(d.getTongDiem()+"");
    }//GEN-LAST:event_tbXemDiemMouseClicked

    private void btnLuuThayDoiDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuThayDoiDiemActionPerformed
        // TODO add your handling code here:
        float DiemGKMoi = Float.parseFloat(edtDiemGK.getText().toString());
        float DiemCKMoi = Float.parseFloat(edtDiemCK.getText().toString());
        float DiemKhacMoi = Float.parseFloat(edtDiemKhac.getText().toString());
        float TongDiemMoi = Float.parseFloat(edtTongDiem.getText().toString());
        
        Diem d = DSDiemCanChinh.get(selectedIndexTB);
        d.setDiemGk(DiemGKMoi);
        d.setDiemCk(DiemCKMoi);
        d.setDiemKhac(DiemKhacMoi);
        d.setTongDiem(TongDiemMoi);
        
        //gọi hàm lưu lại
        QLSVDao.updateDiem(d);
        JOptionPane.showMessageDialog(rootPane, "lưu thành công!");
    }//GEN-LAST:event_btnLuuThayDoiDiemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chf = new JFileChooser();
        int check = chf.showOpenDialog(null);
        if(check==JFileChooser.APPROVE_OPTION)
        {
            
            TKBieu.clear();
            String fileName = chf.getSelectedFile().getPath();
            lbFileTKB.setText(fileName);
            BufferedReader reader;
            String Line;
            try {
                reader = new BufferedReader(new FileReader(fileName));
                Line = reader.readLine();
                int dem=1;
                dfmThemTKB.setRowCount(0);
                while((Line = reader.readLine())!=null)
                {
                    //Line = reader.readLine();
                    List a = pastCSVLine(Line);

                    //Lop lop = new Lop((String)a.get(1),(String)a.get(2),(String)a.get(3),(String)a.get(4),(String)a.get(5));
                    Tkbieu tkb = new Tkbieu((String)a.get(1),(String)a.get(2),(String)a.get(3),(String)a.get(4));
                    TKBieu.add(tkb);

                    dfmThemTKB.addRow(new Object[]{dem++,
                    tkb.getMaMon(),
                    tkb.getTenMon(),
                    tkb.getLop(),
                    tkb.getPhong()
                    });
            }
                reader.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManagerMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ManagerMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnThemTKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTKBActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<TKBieu.size();i++)
        {
            QLSVDao.ThemTKB(TKBieu.get(i));
        }
        JOptionPane.showMessageDialog(rootPane, "thêm thời khóa biểu thành công");
    }//GEN-LAST:event_btnThemTKBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerMenu().setVisible(true);
            }
        });
    }
    
    public static List<String> pastCSVLine(String csvLine)
    {
        List<String> result = new ArrayList<String>();
	if (csvLine != null) {
            String[] splitData = csvLine.split(",");
            for (int i = 0; i < splitData.length; i++)
            {
               result.add(splitData[i]);
            }
        }
	return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonFile;
    private javax.swing.JButton btnChonFileDiemCSV;
    private javax.swing.JButton btnLuuThayDoiDiem;
    private javax.swing.JButton btnThemDSLop;
    private javax.swing.JButton btnThemDiemVaoHT;
    private javax.swing.JButton btnThemSinhVien;
    private javax.swing.JButton btnThemTKB;
    private javax.swing.JButton btnXemDiem;
    private javax.swing.JButton btnXemThongTinLop;
    private javax.swing.JTextField edtCMND;
    private javax.swing.JTextField edtDiemCK;
    private javax.swing.JTextField edtDiemGK;
    private javax.swing.JTextField edtDiemKhac;
    private javax.swing.JTextField edtGioiTinh;
    private javax.swing.JTextField edtHoTen;
    private javax.swing.JTextField edtLop;
    private javax.swing.JTextField edtLopDiem;
    private javax.swing.JTextField edtMSSV;
    private javax.swing.JTextField edtTenLop;
    private javax.swing.JTextField edtTongDiem;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel lbDau;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbFileDiem;
    private javax.swing.JLabel lbFileTKB;
    private javax.swing.JLabel lbMSSV;
    private javax.swing.JLabel lbMon;
    private javax.swing.JLabel lbRot;
    private javax.swing.JLabel lbfile;
    private javax.swing.JTable tbDSLop;
    private javax.swing.JTable tbDiem;
    private javax.swing.JTable tbThemTKB;
    private javax.swing.JTable tbXemDiem;
    private javax.swing.JTable tblop;
    // End of variables declaration//GEN-END:variables
}
