package pojo;
// Generated May 29, 2020 11:00:17 PM by Hibernate Tools 4.3.1



/**
 * Diem generated by hbm2java
 */
public class Diem  implements java.io.Serializable {


     private int stt;
     private String maSv;
     private String maMon;
     private Float diemGk;
     private Float diemCk;
     private Float diemKhac;
     private Float tongDiem;

    public Diem() {
    }

	
    public Diem(int stt) {
        this.stt = stt;
    }
    public Diem(int stt, String maSv, String maMon, Float diemGk, Float diemCk, Float diemKhac, Float tongDiem) {
       this.stt = stt;
       this.maSv = maSv;
       this.maMon = maMon;
       this.diemGk = diemGk;
       this.diemCk = diemCk;
       this.diemKhac = diemKhac;
       this.tongDiem = tongDiem;
    }
   
    public int getStt() {
        return this.stt;
    }
    
    public void setStt(int stt) {
        this.stt = stt;
    }
    public String getMaSv() {
        return this.maSv;
    }
    
    public void setMaSv(String maSv) {
        this.maSv = maSv;
    }
    public String getMaMon() {
        return this.maMon;
    }
    
    public void setMaMon(String maMon) {
        this.maMon = maMon;
    }
    public Float getDiemGk() {
        return this.diemGk;
    }
    
    public void setDiemGk(Float diemGk) {
        this.diemGk = diemGk;
    }
    public Float getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(Float diemCk) {
        this.diemCk = diemCk;
    }
    public Float getDiemKhac() {
        return this.diemKhac;
    }
    
    public void setDiemKhac(Float diemKhac) {
        this.diemKhac = diemKhac;
    }
    public Float getTongDiem() {
        return this.tongDiem;
    }
    
    public void setTongDiem(Float tongDiem) {
        this.tongDiem = tongDiem;
    }




}


