package pojo;
// Generated May 29, 2020 11:00:17 PM by Hibernate Tools 4.3.1



/**
 * Lop generated by hbm2java
 */
public class Lop  implements java.io.Serializable {


     private int stt;
     private String mssv;
     private String hoTen;
     private String gioiTinh;
     private String lop;
     private String cmnd;

    public Lop() {
    }

	
    public Lop(int stt) {
        this.stt = stt;
    }
    public Lop( String mssv, String hoTen, String gioiTinh, String lop, String cmnd) {
       //this.stt = stt;
       this.mssv = mssv;
       this.hoTen = hoTen;
       this.gioiTinh = gioiTinh;
       this.lop = lop;
       this.cmnd = cmnd;
    }
   
    public int getStt() {
        return this.stt;
    }
    
    public void setStt(int stt) {
        this.stt = stt;
    }
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getLop() {
        return this.lop;
    }
    
    public void setLop(String lop) {
        this.lop = lop;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }




}


