package pojo;
// Generated Jun 10, 2020 7:55:54 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tgphuckhao generated by hbm2java
 */
public class Tgphuckhao  implements java.io.Serializable {


     private int stt;
     private Date ngayBd;
     private Date ngayKt;

    public Tgphuckhao() {
    }

	
    public Tgphuckhao(int stt) {
        this.stt = stt;
    }
    public Tgphuckhao(int stt,Date ngayBd, Date ngayKt) {
       this.stt=stt;
       this.ngayBd = ngayBd;
       this.ngayKt = ngayKt;
    }
   
    public int getStt() {
        return this.stt;
    }
    
    public void setStt(int stt) {
        this.stt = stt;
    }
    public Date getNgayBd() {
        return this.ngayBd;
    }
    
    public void setNgayBd(Date ngayBd) {
        this.ngayBd = ngayBd;
    }
    public Date getNgayKt() {
        return this.ngayKt;
    }
    
    public void setNgayKt(Date ngayKt) {
        this.ngayKt = ngayKt;
    }




}


