package pojo;
// Generated May 29, 2020 9:07:42 PM by Hibernate Tools 4.3.1



/**
 * Tkdangnhap generated by hbm2java
 */
public class Tkdangnhap  implements java.io.Serializable {


     private int mssv;
     private String password;
     private Integer isGv;

    public Tkdangnhap() {
    }

	
    public Tkdangnhap(int mssv) {
        this.mssv = mssv;
    }
    public Tkdangnhap(int mssv, String password, Integer isGv) {
       this.mssv = mssv;
       this.password = password;
       this.isGv = isGv;
    }
   
    public int getMssv() {
        return this.mssv;
    }
    
    public void setMssv(int mssv) {
        this.mssv = mssv;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getIsGv() {
        return this.isGv;
    }
    
    public void setIsGv(Integer isGv) {
        this.isGv = isGv;
    }




}


