package pojo;
// Generated Jun 3, 2020 2:23:50 PM by Hibernate Tools 4.3.1



/**
 * Tkdangnhap generated by hbm2java
 */
public class Tkdangnhap  implements java.io.Serializable {


     private String mssv;
     private String password;
     private Integer isGv;

    public Tkdangnhap() {
    }

	
    public Tkdangnhap(String mssv) {
        this.mssv = mssv;
    }
    public Tkdangnhap(String mssv, String password, Integer isGv) {
       this.mssv = mssv;
       this.password = password;
       this.isGv = isGv;
    }
   
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getIsGv() {
        return this.isGv;
    }
    
    public void setIsGv(Integer isGv) {
        this.isGv = isGv;
    }




}


